#!/bin/bash
# A simple bash script to import/export a wordpress database to current wordpress installation directory.
# written by Alfio Salanitri <www.alfiosalanitri.it> and are licensed under MIT license. 

readonly DUMP_NAME='dump.sql'
readonly CURRENT_DIRECTORY=$(pwd)

# Get db config options from wp-config file
readonly FILE_CONFIG="$CURRENT_DIRECTORY/wp-config.php"
if [ ! -f "$FILE_CONFIG" ]; then
  printf "The wp-config.php file doesn't exists. \n"
  exit 1
fi
readonly DB_NAME=$(cat $FILE_CONFIG | grep DB_NAME | cut -d \' -f 4)
readonly DB_USER=$(cat $FILE_CONFIG | grep DB_USER | cut -d \' -f 4)
readonly DB_PASSWORD=$(cat $FILE_CONFIG | grep DB_PASSWORD | cut -d \' -f 4)

display_help() {
cat << EOF
Copyright (C) 2022 by Alfio Salanitri
Website: https://github.com/alfiosalanitri/wp-db-sync

Usage: $(basename $0) -i
Options
-i
    Backup current database to dump.sql.bkp and import dump.sql file
  
-e
    Export database to dump.sql file
    
-h, --help
    show this help
-------------
EOF
exit 0
}

import_db() {
  printf "Importing database...\n"
  mysqldump -u$DB_USER -p$DB_PASSWORD $DB_NAME > "$DUMP_NAME.bkp"
  mysql -u$DB_USER -p$DB_PASSWORD -e "drop database $DB_NAME;"
  mysql -u$DB_USER -p$DB_PASSWORD -e "create database $DB_NAME;"
  mysql -u$DB_USER -p$DB_PASSWORD $DB_NAME < $DUMP_NAME
  printf "Done.\n"
}

export_db() {
  printf "Dumping database...\n"
  mysqldump -u$DB_USER -p$DB_PASSWORD $DB_NAME > $DUMP_NAME
  printf "Done.\n"
}

if [ ! "$1" ]; then
  display_help
  exit 1
fi

while [ $# -gt 0 ] ; do
  case $1 in
    -h | --help) display_help ;;
    -i) import_db;;
    -e) export_db;;
  esac
  shift
done
exit 0
